kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.serviceApp.port }}
              scheme: HTTP
            periodSeconds: 60
            timeoutSeconds: 20
            initialDelaySeconds: 65
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.serviceApp.port }}
              scheme: HTTP
            initialDelaySeconds: 65
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: saprykin-test-app
          ports:
            - name: http
              containerPort: {{ .Values.serviceApp.port }}
              protocol: TCP
          imagePullPolicy: {{ .Values.imageApp.pullPolicy }}
          terminationMessagePolicy: File
          image: {{ .Values.imageApp.repository }}:{{ .Values.imageApp.tag }}
      serviceAccount: default
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600